services:
  api:
    build: ./backend
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
    ports:
      - "8000:8000"
    env_file: ./.env
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
