services:
  api:
    build: ./backend
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8088"]
    ports:
      - "8088:8088"
    env_file: ./.env
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file: ./.env
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    restart: unless-stopped
